ui/View.elm

Trying something a bit different for the display of "filters information":
The idea is to replace the select boxes with the "filter info" label, to avoid having a select box with only the "all" and the selected filter options, making it (maybe?) a bit more ergonomic.
@n1k0 what do you think?

Merge filterInfos in the filter sidebar

---

jobs/buildhub/utils.py
jobs/setup.py
jobs/tests/test_scrape_archives.py
jobs/tests/test_utils.py

Refs #69 
This tests shows that with the right record, the ID is correct. Which means that we don't build the right record for the Fennec nightly URLs.

Supports Fennec URLs

---

ui/Main.elm
ui/Model.elm
ui/Types.elm
ui/View.elm
ui/elm-package.json

Note: this is not intended for landing as is. This patch illustrates how the new elm-kinto pagination system works, with a working implementation.
We'll definitely wait for #40 to land first before landing this, especially as this can't fully work with in-memory filtering.

Paginate build list.

---

ui/src/Main.elm
ui/src/Types.elm
ui/src/Url.elm
ui/src/View.elm

Fixes #89. This patch wraps current filters into a form you submit as a whole everytime you want to refine your current search.
- It saves a bunch of http requests
- It reallows filtering build ids along other filters
- Usage is a little less *dynamic* as you need to submit the form to run a search.
Thoughts?

Fix #89: Update filters so they act like a form.

---

ui/src/View.elm

Addresses #141. This patch conditionally removes the count info for the `all` filter value when a value is already selected for that specific filter, to avoid confusion.

Fix #141: Remove count info for filters 'all' value.

---

ui/elastic/src/App.js

Refs #149 : this is a (maybe?) stopgap solution to filtering versions naively on the frontend.

[searchkit] Order version numbers on the frontend

---

ui/elastic/src/App.js
ui/elastic/src/index.css

Refs #170 : live search on all fields in searchkit
Deployed at https://mozilla-services.github.io/buildhub/searchkit
The difference here with #170 is that there isn't automatic `*` added to the search terms, you need to put them yourself. Searching for `fire` won't return any result, but `fire*` will.

Search on all fields

---

jobs/buildhub/utils.py
jobs/tests/test_utils.py
jobs/tox.ini

I was looking over the buildhub code and discovered that it doesn't detect "channel" for Firefox ESRs correctly - it sets it to "release" instead of "esr". This patch fixes that, but still needs to be updated to either make it work for Thunderbird (or fix the tests if it already does).
Thunderbird is a bit of a weird case because their "release" channel is built out of ESR repositories - so it's not exactly comparable to Firefox.

Fix esr channel detection for Firefox.

---

jobs/README.rst
jobs/buildhub/inventory_to_records.py
jobs/buildhub/utils.py
jobs/tests/data/inventory-simple.csv
jobs/tests/test_utils.py

Use archive inventory and limit products to process (Fixes #193)

---

.travis.yml
jobs/buildhub/inventory_to_records.py
jobs/buildhub/lambda_s3_inventory.py
jobs/buildhub/to_kinto.py
jobs/buildhub/utils.py
jobs/setup.py
jobs/tests/test_inventory_to_records.py
jobs/tests/test_inventory_to_records_functional.py
jobs/tests/test_lamdba_s3_inventory.py
jobs/tox.ini

fixes #197
> **Note**: This PR drops support of Python 3.5 because we now use async generators of Python 3.6.

Lambda to load S3 inventories  (fixes #197)

---

jobs/buildhub/lambda_s3_inventory.py

Ref #223 
Big thanks @mjpieters for his insights :)

Add comment about gzip decompressor (ref #223)

---

jobs/buildhub/utils.py
jobs/tests/data/inventory-simple.csv
jobs/tests/test_inventory_to_records_functional.py
jobs/tests/test_utils.py

Fixes #188 
@mozbhearsum in the issue description you said we should treat devedition builds as firefox builds. But in that case how should distinguish them from firefox aurora builds?

Handle devedition builds (fixes #188)

---

jobs/CHANGELOG.rst
jobs/buildhub/lambda_s3_event.py
jobs/tests/data/s3-event-simple.json
jobs/tests/test_lamdba_s3_event.py

fixes #253 
I have no idea how I came up with the idea that `eventTime` was on the top mapping, whereas every example out there has `eventTime` within the mapping of each record...

Fix S3 event eventTime key error (fixes #253)

---

.dockerignore
Makefile
bin/run.sh

It was completely broken !
* It failed writing `lambda.zip` to `/app` (read-only)
* It failed naming the container with `/`
* It was copying hundreds of megabytes (`.venv`, `.tox`)

Fix lambda archive build

---

jobs/CHANGELOG.rst
jobs/buildhub/inventory_to_records.py
jobs/buildhub/lambda_s3_inventory.py
jobs/buildhub/utils.py
jobs/tests/test_inventory_to_records.py
jobs/tests/test_inventory_to_records_functional.py
jobs/tests/test_utils.py

The more I think of it, the more I think we should get rid of the records without ids.
On stage we almost have like a million records, this is nuts.
This PR skips the records without build id.

Skip incomplete by default

---

jobs/CHANGELOG.rst
jobs/buildhub/inventory_to_records.py
jobs/tests/test_inventory_to_records.py

@Natim I can't figure out why the `mock` has no effect...

Keep trace but skip build urls that have unsupported formats

---

jobs/buildhub/inventory_to_records.py
jobs/buildhub/lambda_s3_event.py
jobs/buildhub/lambda_s3_inventory.py
jobs/tests/test_lamdba_s3_event.py
jobs/tests/test_to_kinto.py

The problem was due to the fact that our tests didn't return a 404 HTML response but a connection refused when the URL was not mocked by `aiohttpresponses`
Fixes #296

Fix missing metadata for nightly archives (Fixes #296)

---

jobs/CHANGELOG.rst
jobs/buildhub/utils.py
jobs/tests/test_utils.py

Prevent test_packages metadata from being recognized as release metadata (fixes #295)

---

.dockerignore
Dockerfile
jobs/CHANGELOG.rst

fixes #299
```
---> Running in 634387a386d4
virtualenv --python=python3.6 .venv --python=python3.6
Using base prefix '/usr/local'
New python executable in /app/.venv/bin/python3.6
Also creating executable in /app/.venv/bin/python
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /usr/local/bin/python3.6
Processing ./jobs
Collecting aiobotocore==0.4.5 (from -c jobs/requirements.txt (line 1))
Downloading aiobotocore-0.4.5-py3-none-any.whl
Collecting aiohttp==2.3.0 (from -c jobs/requirements.txt (line 2))
Downloading aiohttp-2.3.0-cp36-cp36m-manylinux1_x86_64.whl (661kB)
Collecting async-timeout==2.0.0 (from -c jobs/requirements.txt (line 3))
Downloading async_timeout-2.0.0-py3-none-any.whl
Collecting backoff==1.4.3 (from -c jobs/requirements.txt (line 4)) …
```

Use requirements.txt versions when building the container (fixes #299)

---

jobs/CHANGELOG.rst
jobs/buildhub/utils.py
jobs/tests/test_utils.py

Fix test_packages regexp to avoid confusion with build metadata (fixes #295, #309)

---

jobs/CHANGELOG.rst
jobs/buildhub/utils.py
jobs/tests/test_utils.py

Fixes #312 
I still excluded the nightly ESR releases. Is that OK @calixteman?

Fix exclusion of thunderbird nightly releases (fixes #312)

---

jobs/CHANGELOG.rst
jobs/buildhub/utils.py
jobs/tests/test_utils.py

Prevent mozinfo JSON files to be mistaken as Nightly metadata (fixes #315)

---

jobs/buildhub/inventory_to_records.py
jobs/dev-requirements.txt
jobs/tests/test_inventory_to_records.py

ref #327 
We've seen a lot of `text/html` errors lately
I suspect them to be 404 because of some kind of latency/race condition while reaching S3 through bucketlister (https://github.com/mozilla-services/product-delivery-tools/tree/master/bucketlister)
This PR will retry requests when receiving non `200 OK` responses. It does no harm and could help but it might also be flogging a dead horse...

Retry fetch JSON when status is not 200 (ref #327)

---

README.md

I've found instructions like these incredibly helpful in Kinto-related projects. This is just the set of steps I understood from Mathieu in chat this morning.

Document the release procedure
