README.md, ui/.gitignore, ui/Main.elm, ui/elm-package.json, ui/index.html, ui/package.json, ui/style.css
=> [ui] Elm app bootstrap.

pulseworker/README.rst, pulseworker/main.py, pulseworker/requirements.txt, pulseworker/tests.py
=> Add Pulse listener

ui/Main.elm, ui/Model.elm, ui/Types.elm, ui/View.elm
Quick and dirty, deployed to prod. Feedback wanted.
=> Add a build id filter.

ui/Main.elm, ui/Types.elm, ui/View.elm, ui/style.css
This is preliminary refactoring of the views before starting tackling #9. 
I removed the fixed sidebar thing, which was ugly and malfunctioning. I switched the many radio buttons to be just simple dropdowns, which I'm finding quite usable and gains us a lot of real estate.
Feedback? @magopian
=> Preliminary UI refactoring before #9

ui/Main.elm, ui/Model.elm, ui/Snippet.elm, ui/Types.elm, ui/View.elm
=> Fix #9: Added docs and snippets.

jobs/README.rst
=> Typo in reST

jobs/listen_pulse.py, jobs/requirements.txt, jobs/scrape_archives.py, jobs/sysaddons_updates.py
default_retry was added late in the 7.x series.
=> Upgrade to kinto-http.py 8.0.1

jobs/CHANGELOG.rst, jobs/buildhub/scrape_archives.py, jobs/buildhub/utils.py, jobs/tests/test_scrape_archives.py, jobs/tests/test_utils.py
=> Glasserc fix mimetype

jobs/CHANGELOG.rst, jobs/buildhub/scrape_archives.py, jobs/buildhub/utils.py, jobs/tests/test_scrape_archives.py, jobs/tests/test_utils.py
=> Infer channel from URL (fixes #8)

ui/Main.elm, ui/Model.elm, ui/Types.elm, ui/Url.elm, ui/View.elm, ui/elm-package.json
=> URLify the web UI

jobs/buildhub/scrape_archives.py
Fixes #60 
@Natim what do you think? In the end, I prefer this compared to the `--strict` option approach I had yesterday.
=> Raise exceptions for 4XX responses in batch results (fixes #60)

jobs/buildhub/scrape_archives.py, ui/Decoder.elm, ui/Model.elm, ui/Types.elm, ui/View.elm
This is a first step in order to build a Kinto compatible JSONSchema.
=> Remove null values.

ui/View.elm, ui/elm-package.json
=> Display size in Human readable format.

.travis.yml, ui/View.elm, ui/package.json
The goal of this PR is to add the Travis configuration.
However I did a bit of cleanup and add @glasserc review to rename ``format`` into ``formatFilesize``
=> Travis config

ui/View.elm, ui/elm-package.json
Refs https://github.com/basti1302/elm-human-readable-filesize/pull/1
=> Since v1.1.0 we can use Filesize.formatBase2.

ui/View.elm
=> Change filters back to simple SELECTs

ui/Main.elm
=> Remove duplicate request to Kinto

ui/Model.elm
Fixes #86 (temporary workaround https://github.com/Kinto/kinto/issues/1217)
=> Surround version numbers by quotes when sending request to Kinto

ui/README.md, ui/package.json
Build size is now 152k instead of 526k.
=> Fix #96: Optimize production build.

ui/src/Main.elm, ui/src/Model.elm, ui/src/Types.elm, ui/src/View.elm
=> Display the error messages on the UI

ui/src/Main.elm, ui/src/Types.elm, ui/src/View.elm
=> Add a button to dismiss an error message

jobs/buildhub/index_filters.py, jobs/setup.py, jobs/tests/test_index_filters.py
=> Add a CLI tool to rebuild the list of filters.

ui/src/Types.elm, ui/src/Url.elm
=> Remove useless routes

ui/src/Main.elm, ui/src/Model.elm, ui/src/Types.elm, ui/src/View.elm
=> Increase the number of builds to display per page to 100

ui/src/View.elm
=> Change build permalinks to be based on product-platform-version-locale

ui/elm-package.json, ui/public/style.css, ui/src/Decoder.elm, ui/src/ElasticSearch.elm, ui/src/Main.elm, ui/src/Model.elm, ui/src/Types.elm, ui/src/Url.elm, ui/src/View.elm
=> Fix #117: Implement faceted search.

ui/src/ElasticSearch.elm
=> Fix #137: Sort locales alphabetically

jobs/buildhub/scrape_archives.py, jobs/buildhub/utils.py, jobs/initialization.yml, jobs/tests/test_utils.py
=> Scrape all available build-ids for all releases.

jobs/buildhub/scrape_archives.py, jobs/buildhub/utils.py, jobs/tests/test_utils.py
Fixes https://github.com/mozilla-services/buildhub/issues/120
=> Use macosx as a platform for nightly builds.

ui/elastic/package.json, ui/elastic/src/App.js, ui/elastic/src/index.css
=> Another attempt at improving the styling for #150

ui/public/style.css, ui/src/ElasticSearch.elm, ui/src/Init.elm, ui/src/Types.elm, ui/src/Update.elm, ui/src/Url.elm, ui/src/View.elm
Feedback wanted, deployed to https://mozilla-services.github.io/buildhub/
=> Live search box

ui/public/style.css, ui/src/ElasticSearch.elm, ui/src/Init.elm, ui/src/View.elm
=> Fix #106: Use a regular table for listing records.

ui/public/style.css, ui/src/Init.elm, ui/src/Types.elm, ui/src/Update.elm, ui/src/View.elm
Refs #180, patch deployed to gh-pages, cc @willkg
=> Fix #180: Collapsible build details.

jobs/buildhub/scrape_archives.py
Fix #169.
Just a tiny PR to get my feet wet with the backend part of this..
=> Deduplicate EXEs against Zip archives

ui/elastic/src/App.js, ui/elastic/src/index.css
=> Add a link to the Elasticsearch query string syntax documentation

jobs/buildhub/inventory_to_records.py, jobs/tests/data/inventory-simple.csv, jobs/tests/test_inventory_to_records_functional.py
=> Deduplicate linux installers (fixes #195)

jobs/buildhub/utils.py, jobs/tests/test_utils.py
=> Skip namoroka (fixes #192)

jobs/CHANGELOG.rst, jobs/README.rst, jobs/buildhub/inventory_to_records.py, jobs/buildhub/to_kinto.py, jobs/buildhub/utils.py, jobs/initialization.yml, jobs/tests/test_utils.py
=> More consistent usage of archive|release|build (fixes #35)

jobs/buildhub/utils.py, jobs/initialization.yml, jobs/tests/test_inventory_to_records.py, jobs/tests/test_inventory_to_records_functional.py, jobs/tests/test_utils.py
=> Add OS field as normalized platform (fixes #184)

jobs/buildhub/inventory_to_records.py, jobs/buildhub/utils.py, jobs/initialization.yml, jobs/tests/data/inventory-simple.csv, jobs/tests/test_inventory_to_records.py, jobs/tests/test_inventory_to_records_functional.py, jobs/tests/test_utils.py
=> Store release candidates

jobs/buildhub/inventory_to_records.py, jobs/tests/test_inventory_to_records.py, jobs/tests/test_utils.py
=> Fix eme free and sha1 repacks (fixes #203)

jobs/buildhub/lambda_s3_inventory.py, jobs/buildhub/to_kinto.py
=> Increase chunk size and add debug logging (ref #197)

README.md
=> Add Travis tag in README (fixes #211)

jobs/buildhub/lambda_s3_inventory.py, jobs/tests/test_lamdba_s3_inventory.py
=> Fix building of manifest key (ref #197)

jobs/buildhub/utils.py, jobs/initialization.yml, jobs/tests/test_inventory_to_records.py, jobs/tests/test_inventory_to_records_functional.py, jobs/tests/test_lamdba_s3_event.py, jobs/tests/test_lamdba_s3_event_functional.py
=> Add more build metadata (fixes #54)

jobs/buildhub/lambda_s3_inventory.py
=> Do not reuse gzip decompressor instance (fixes #223)

jobs/buildhub/lambda_s3_inventory.py, jobs/buildhub/utils.py, jobs/tests/test_utils.py
=> Skip old wince/winmo alpha builds of Fennec (fixes #224)

jobs/buildhub/utils.py, jobs/tests/test_utils.py
=> Fix unknown platform eabi-arm (fixes #229)

jobs/buildhub/inventory_to_records.py, jobs/buildhub/lambda_s3_event.py, jobs/buildhub/lambda_s3_inventory.py, jobs/buildhub/to_kinto.py, jobs/buildhub/utils.py
$ pip install unify
$ find buildhub -name "*.py" | xargs unify --in-place
=> Use single quotes everywhere

docs/jobs.rst, jobs/buildhub/lambda_s3_inventory.py
To avoid confusions between `build-hub`, `buildhub`...
=> Add safety check for destination bucket/collection

.travis.yml
=> Do not install Kinto for Flake8 job (fixes #214)

jobs/buildhub/lambda_s3_event.py, jobs/buildhub/lambda_s3_inventory.py, jobs/setup.py
=> Add Sentry logging (fixes #241)

jobs/CHANGELOG.rst, jobs/buildhub/inventory_to_records.py, jobs/buildhub/lambda_s3_event.py, jobs/buildhub/lambda_s3_inventory.py, jobs/buildhub/to_kinto.py, jobs/buildhub/utils.py, jobs/tests/data/inventory-simple.csv, jobs/tests/test_inventory_to_records.py, jobs/tests/test_inventory_to_records_functional.py, jobs/tests/test_lamdba_s3_event.py, jobs/tests/test_lamdba_s3_event_functional.py, jobs/tests/test_lamdba_s3_inventory.py, jobs/tests/test_to_kinto.py, jobs/tests/test_utils.py
=> Fix MacOSX metadata URLs (fixes #261)

jobs/CHANGELOG.rst, jobs/buildhub/utils.py, jobs/tests/test_utils.py
=> Skip exe installers where version is missing from URL (fixes #263)

jobs/CHANGELOG.rst, jobs/buildhub/utils.py, jobs/tests/data/inventory-simple.csv, jobs/tests/test_inventory_to_records_functional.py, jobs/tests/test_utils.py
=> Fix Fennec metadata location (fixes #264)

jobs/buildhub/inventory_to_records.py
=> Cache metadata between runs (fixes #265)

jobs/CHANGELOG.rst, jobs/buildhub/inventory_to_records.py, jobs/tests/test_inventory_to_records.py
=> Fix Mac and Windows metadata URLs from installers (fixes #269)

jobs/buildhub/inventory_to_records.py, jobs/buildhub/utils.py, jobs/tests/test_inventory_to_records.py, jobs/tests/test_utils.py
=>  Fix RC fennec metadata URL (fixes #274) 

jobs/CHANGELOG.rst, jobs/buildhub/inventory_to_records.py, jobs/tests/test_inventory_to_records.py
=> Fix handling of bad server response, like XML (fixes #259)

jobs/CHANGELOG.rst, jobs/buildhub/inventory_to_records.py, jobs/tests/test_inventory_to_records.py
=> Fix caching when partial updates metadata is missing (fixes #276)

jobs/CHANGELOG.rst, jobs/buildhub/lambda_s3_event.py, jobs/tests/test_lamdba_s3_event.py
=> Add support for SNS events.

jobs/CHANGELOG.rst, jobs/buildhub/utils.py, jobs/tests/test_utils.py
=> Skip very old RC release with parenthesis in filenames (fixes #288)

jobs/CHANGELOG.rst, jobs/buildhub/utils.py, jobs/tests/test_utils.py
=> Fix support of some funnelcake archives (fixes #287)

docs/api.rst, jobs/tests/test_inventory_to_records_functional.py, ui/package.json, ui/src/App.js
@Natim  can you remove `/dev/` from UI in the hairy `deploy` command from `package.json` (I spent 10min on it and gave up...)
=> Get rid of dev instance

docs/api.rst
=> Fix querystring example for build ids

jobs/CHANGELOG.rst, jobs/buildhub/lambda_s3_event.py, jobs/tests/test_lamdba_s3_event.py
=> Fix event handling of RC metadata (fixes #314)

ui/src/App.js
=> Use classic ISO format for publication date (fixes #320)

ui/src/App.js
=> Improve search placeholder (fixes #305)

contribute.json
This is just a start to tackle https://github.com/mozilla-services/buildhub/issues/319
Once this is reviewed, we need to get it into `gh-pages` somehow.
=> contribute.json

ui/src/App.js
=> Add link to Kinto record (fixes #286)

jobs/CHANGELOG.rst, jobs/buildhub/inventory_to_records.py, jobs/tests/test_inventory_to_records.py
=> Fix build folder ordering (fixes #328)

jobs/CHANGELOG.rst, jobs/buildhub/lambda_s3_inventory.py, jobs/tests/test_lamdba_s3_inventory.py
Try to address https://bugzilla.mozilla.org/show_bug.cgi?id=1437931 by skipping anything that doesn't look exactly like a date.
=> Try to avoid more non-manifest-containing subdirectories

ui/src/App.js
ref #338 
I find this more consistent than on the version column
=> Archive link on file size column (ref #338)

ui/src/App.js, ui/src/index.css
=> Add deprecation notice

README.md, bin/make-release.py
This fixes bin/make-release.py to run in a docker container.
=> Fix release process

README.md, ui/package.json, ui/yarn.lock
We haven't deployed the ui in over a year. I hit a bunch of problems
trying to get it to work. This probably fixes some of them and also
gets rid of all the "stage" deploy things.
=> Redo ui deploys

README.md
This fixes the steps and adds a note about the thing I just removed.
=> Update ui deploy
